#pragma config(Motor,  port1,           top,           tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port2,           left,          tmotorVex393, openLoop)
#pragma config(Motor,  port4,           right,         tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port10,          bot,           tmotorVex393, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){
	int power = 0;
	while(1)
	{
		power ++;
		if(power > 127) power = 127;


		motor[bot] = power;
		motor[top] = power;
		motor[left] = power;
		motor[right] = power;
		wait1Msec(20);
	}
}
