#pragma config(Sensor, dgtl1,  leftEnc,        sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  rightEnc,       sensorQuadEncoder)
#pragma config(Motor,  port2,           shooter2,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           left1,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           intake2,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           intake1,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           shooter1,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           right1,        tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){
	while(1){
		motor[shooter1] = 60;
	}
}
