#pragma config(Motor,  port2,           left,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           shooter2,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           shooter1,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           intake2,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           intake1,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           right,         tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "Functions.h"
#include "Main.h"
#include "Drive.h"
#include "Accessory.h"
#include "MotionProfiling.h"
#include "Functions.c"
#include "Drive.c"
#include "Accessory.c"
#include "MotionProfiling.c"
#include "Main.c"

task main(){
	makeValues(0,0,0);
	while(1){
		mainDrive();
	}
}
